controller_joint_names: ['', 'rearwheelsjoints', 'FrontLeftWheelJoint', 'FrontRightWheelJoint', 'left_frontaxisjoint', 'right_frontaxisjoint' ]

toycar:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------

  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_frontaxisjoint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  #   # pid_gains:
  #   #   p: 100.0
  #   #   i: 0.01 
  #   #   d: 10.0
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_frontaxisjoint
    pid: {p: 100.0, i: 0.01, d: 10.0}
    # pid_gains:
    #   p: 100.0
    #   i: 0.01 
    #   d: 10.0

  joint3_position_controller:
    type: velocity_controllers/JointVelocityController
    joint: rearwheelsjoints
    pid: {p: 100.0, i: 0.01, d: 10.0}



# /gazebo_ros_control:   
#   pid_gains:
    
    # FrontRightWheelJoint:
    #   p: 100.0
    #   i: 0.01 
    #   d: 10.0

    # FrontLeftWheelJoint:
    #   p: 100.0
    #   i: 0.01 
    #   d: 10.0

    # rearwheelsjoints:
    #   p: 100.0
    #   i: 0.01 
    #   d: 10.0